# Main scons SConstruct file. Tested working with OSX 10.9 & Cygwin (g++, scons, python package installed)
# You can use 'watchr' or something similar to rebuild every time some files changed in src or test.

# todo only build gtest if lib not yet found. + in separate build files
env = Environment(CXX = 'g++')	# gtest is using std::string etc, so no gcc.

gtest = env.SConscript('lib/gtest/SConscript', 'env')
src = env.SConscript('src/SConscript', 'env')
out = env.SConscript('test/SConscript', 'env gtest src')

# output is an array with path to built binaries. We only built one file - run it (includes gtest_main).
test = Command( target = "testoutput",
                source = str(out[0]),
                action = str(out[0]) )
AlwaysBuild(test)
