require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << '.'	# could be 'app' meaning one can require 'file' instead of 'app/file' in the test ruby files
  t.test_files = FileList['test/test_*.rb']
  t.verbose = true
end

task :default => :test
