env = Environment(CXX = 'g++', CPPPATH = './:#src/:#/../../lib/C++/gtest/include')

gtest = env.SConscript('./../../lib/C++/gtest/SConscript', 'env')
src = env.SConscript('src/SConscript', 'env')
out = env.SConscript('test/SConscript', 'env gtest src')

# output is an array with path to built binaries. We only built one file - run it (includes gtest_main).
test = Command( target = "testoutput",
                source = str(out[0]),
                action = str(out[0]) )
AlwaysBuild(test)
